Add crossScalaVersions directly in build.sbt (#2072)

diff --git a/.github/scripts/exec-sbt-command b/.github/scripts/exec-sbt-command
--- a/.github/scripts/exec-sbt-command
+++ b/.github/scripts/exec-sbt-command
@@ -6,14 +6,14 @@ cd "$(dirname "$0")/../.." || exit
 
 echo
 echo "--------------------------------"
-echo "SCALA_VERSION   = $SCALA_VERSION"
+echo "SCALA_COMMAND   = $SCALA_COMMAND"
 echo "SBT_COMMAND     = $SBT_COMMAND"
 echo "PLATFORM        = $PLATFORM"
 echo "--------------------------------"
 echo
 
-if [[ -z "$SCALA_VERSION" ]]; then
-    echo "ERROR: environment value SCALA_VERSION is not set!" 1>&2
+if [[ -z "$SCALA_COMMAND" ]]; then
+    echo "ERROR: environment value SCALA_COMMAND is not set!" 1>&2
     exit 1
 fi
 
@@ -22,4 +22,4 @@ if [[ -z "$SBT_COMMAND" ]]; then
     exit 1
 fi
 
-sbt -J-Xmx6144m ++$SCALA_VERSION $SBT_COMMAND
+sbt -J-Xmx6144m ";$SCALA_COMMAND;$SBT_COMMAND"
