Fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -214,15 +214,23 @@ jobs:
       - name: Install GnuPG2
         run: |
           sudo apt-get update && sudo apt-get -y install gnupg2
+          echo "Creating directory ~/.gnupg"
           mkdir ~/.gnupg && chmod 700 ~/.gnupg
+          echo "Updating ~/.gnupg/gpg.conf"
           echo use-agent >> ~/.gnupg/gpg.conf
           echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
           echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
           chmod 600 ~/.gnupg/*
+          echo "Reloading agent (via gpg-connect-agent)"
           echo RELOADAGENT | gpg-connect-agent
+          if [ -z "$PGP_SECRET" ]; then
+            echo "ERROR: PGP_SECRET is not set!" >&2
+            exit 1
+          fi
+          echo "Importing PGP_SECRET"
           echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
         env:
-          PGP_SECRET: ${{secrets.PGP_SECRET}}
+          PGP_SECRET: ${{ secrets.PGP_SECRET }}
 
       - name: SCALAJS_VERSION=${{ matrix.scalajs }} sbt ci-release
         run: |
